FROM questdb/questdb:latest

# Set time zone (IST) if possible, but skip installation if pkg manager missing
ENV TZ=Asia/Kolkata

# Custom configuration can be added here in the future
# e.g., COPY server.conf /var/lib/questdb/conf/server.conf
