#pragma once

#include <cstdint>
#include "InstrumentInfo.hpp"
#include "TaxCalculator.hpp"

namespace alpha::market {

/**
 * @brief Immutable record of a single paper-traded fill.
 * Generated by ExecutionSimulator when an OrderIntent is processed.
 */
struct Trade {
    uint64_t     trade_id;
    uint64_t     timestamp_ns;
    uint32_t     instrument_token;
    char         symbol[32];
    Segment      segment;
    int32_t      qty;              // Absolute units filled
    int32_t      side;             // 1=BUY, -1=SELL
    double       signal_price;     // Price from OrderIntent
    double       fill_price;       // Actual fill (signal_price ± slippage)
    double       lot_size;
    double       turnover;         // qty × fill_price × lot_size

    TaxBreakdown charges;          // Full charge breakdown
    double       net_amount;       // side × turnover − total_charges (cash impact)
    double       confidence;
    uint32_t     strategy_id;
    int32_t      order_reason;     // 1=ENTRY, 2=EXIT, 3=SCALE_IN, 4=SCALE_OUT, 5=REVERSE
};

} // namespace alpha::market
